/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEVMAccounts,
  IEVMAccountsInterface,
} from "../../../contracts/evm-accounts/IEVMAccounts";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "accountId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "evmAddress",
        type: "address",
      },
    ],
    name: "ClaimAccount",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "accountId",
        type: "bytes32",
      },
    ],
    name: "claimDefaultEvmAddress",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "evmAddress",
        type: "address",
      },
    ],
    name: "getAccountId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "accountId",
        type: "bytes32",
      },
    ],
    name: "getEvmAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEVMAccounts__factory {
  static readonly abi = _abi;
  static createInterface(): IEVMAccountsInterface {
    return new utils.Interface(_abi) as IEVMAccountsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEVMAccounts {
    return new Contract(address, _abi, signerOrProvider) as IEVMAccounts;
  }
}
