/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EVMAccounts__factory } from "./EVMAccounts__factory";
export { IEVMAccounts__factory } from "./IEVMAccounts__factory";
