/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as acalaAddressSol from "./AcalaAddress.sol";
export * as karuraAddressSol from "./KaruraAddress.sol";
export * as mandalaAddressSol from "./MandalaAddress.sol";
