/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IStableAsset__factory } from "./IStableAsset__factory";
export { StableAsset__factory } from "./StableAsset__factory";
