/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Incentives } from "./Incentives";
export type { InterfaceIncentives } from "./InterfaceIncentives";
