/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IXtokens__factory } from "./IXtokens__factory";
export { Xtokens__factory } from "./Xtokens__factory";
