/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as acalaAddressSol from "./AcalaAddress.sol";
export type { acalaAddressSol };
import type * as karuraAddressSol from "./KaruraAddress.sol";
export type { karuraAddressSol };
import type * as mandalaAddressSol from "./MandalaAddress.sol";
export type { mandalaAddressSol };
